### ISSUE TITLE
当运行 DBCNN.py时报错

### ISSUE THREAD

**Issue by Drangonliao123** [zwx8981/DBCNN-PyTorch#32]
当运行DBCNN.py时报错：
Traceback (most recent call last):
  File "/home/dell/LGL/DBCNN-PyTorch-master/DBCNN.py", line 354, in <module>
    main()
  File "/home/dell/LGL/DBCNN-PyTorch-master/DBCNN.py", line 336, in main
    manager = DBCNNManager(options, path)
  File "/home/dell/LGL/DBCNN-PyTorch-master/DBCNN.py", line 169, in __init__
    transform=train_transforms)
  File "/home/dell/LGL/DBCNN-PyTorch-master/LIVEFolder.py", line 61, in __init__
    self.labels = self.dmos['dmos_new'].astype(np.float32)   
KeyError: 'dmos_new'

请问这是哪里出了问题，万分感谢！

**Comment by zwx8981** [comment]
@Drangonliao123 你需要从live数据库的官网下载数据集和realigned_dmos
